2025-06-18 09:52:22,450 - orion_utils - ERROR - Failed to send data to Orion: HTTPConnectionPool(host='192.168.188.201', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d63974ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-18 09:52:22,452 - __main__ - ERROR - Error processing SERVER1.SLAVE1: HTTPConnectionPool(host='192.168.188.201', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d63974ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
